insert into product (name, min_period, max_period, create_dtime, update_dtime) values ('여행자 보험', 1, 3, now(), now())
insert into product (name, min_period, max_period, create_dtime, update_dtime) values ('휴대폰 보험', 1, 12, now(), now())
insert into coverage (name, coverage, base, create_dtime, update_dtime) values ('상해 치료비', 1000000, 100, now(), now())
insert into coverage (name, coverage, base, create_dtime, update_dtime) values ('항공기 지연 도착 시 보상금', 500000, 100, now(), now())
insert into coverage (name, coverage, base, create_dtime, update_dtime) values ('부분 손실', 750000, 100, now(), now())
insert into coverage (name, coverage, base, create_dtime, update_dtime) values ('전체 손실', 1570000, 40, now(), now())
insert into product_coverage_map (product_seq, coverage_seq, use_yn, create_dtime, update_dtime) values (1,1,1,now(), now())
insert into product_coverage_map (product_seq, coverage_seq, use_yn, create_dtime, update_dtime) values (1,2,1,now(), now())
insert into product_coverage_map (product_seq, coverage_seq, use_yn, create_dtime, update_dtime) values (2,3,1,now(), now())
insert into product_coverage_map (product_seq, coverage_seq, use_yn, create_dtime, update_dtime) values (2,4,1,now(), now())
select 1